runtime: custom
env: flex

service: banditgames-app

network:
  name: projects/shared-vpc-host-447502/global/networks/my-shared-vpc
  subnetwork_name: subnet-services-front

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2