runtime: nodejs18
env: standard

service: banditgames-app

vpc_access_connector:
  name: projects/banditgames-front/locations/europe-west1/connectors/my-vpc-connector

manual_scaling:
  instances: 1

env_variables:
  VITE_LOCAL_BASE_URL: "https://internal.local/gameplatform"
  VITE_LOCAL_STATISTICS_URL: "https://internal.local/statistics"
  VITE_REACT_APP_URL: "http://localhost:5173/"
  VITE_KC_URL: "https://keycloak-service-dot-checkers-test-447118.ew.r.appspot.com/"
  VITE_KC_REALM: "Bandit Games"
  VITE_KC_CLIENT_ID: "platform-client"