runtime: nodejs18
env: standard

service: checkersgame-app

vpc_access_connector:
  name: projects/banditgames-front/locations/europe-west1/connectors/my-vpc-connector
  egress_setting: all-traffic

automatic_scaling:
  min_idle_instances: 2