stages:
  - security-test
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

sast:
  stage: security-test
secret_detection:
  stage: security-test
dependency_scanning:
  stage: security-test

checkersgames-trigger-gcb:
  image: google/cloud-sdk:latest
  stage: deploy
  identity: google_cloud
  script:
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud builds triggers run checkersgame-app --region=europe-west1
