stages:
  - security-test
  - deploy

checkersgames-trigger-gcb:
  image: google/cloud-sdk:latest
  stage: deploy
  identity: google_cloud
  script:
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud builds triggers run checkersgame-app --region=europe-west1
